deptofdefense/move.mil

- src/_assets/javascripts/application.js
- src/_assets/javascripts/components/moving-allowances.js
- src/_assets/stylesheets/application.scss
- src/_assets/stylesheets/components/_forms.scss
- src/_assets/stylesheets/components/_section.scss
- src/_assets/stylesheets/elements/_inputs.scss
- src/_layouts/application.html
- src/_vendor/assets/javascripts/jquery/jquery.js
- src/_vendor/assets/stylesheets/uswds/elements/_inputs.scss
- src/moving-allowances/determine-your-allowance/index.html
I have…
**Note:** The test suite does not currently pass owing to some `<a href="#TODO">` anchors in the content.
This pull request allows a user to select their rank from a list and view the entitlements available to them based on the provided rank. It _does not yet_ implement search across the dependency status and move type `<select>`s. A forthcoming PR will address those shortcomings.
From a technical perspective, this PR adds [jQuery](http://jquery.com/) (version 3.2.1) to the vendor'ed assets and establishes a rough (and imperfect) pattern for developing and implementing JavaScript components. The current strategy relies on fairly uniquely-named components (`MovingAllowances`, in this case) which are methods attached to `window` and instantiated with the `new` keyword. _This is by …
> Enhance Moving Allowances page

- lib/rake/tasks/htmlproofer.rake
- src/_assets/stylesheets/components/_layout.scss
- src/_assets/stylesheets/elements/_typography.scss
- src/_data/navigation.yml
- src/schedule-your-move/access-dps-via-eta/index.html
- src/schedule-your-move/estimate-weight-allowance/index.html
- src/schedule-your-move/index.html
- src/schedule-your-move/learn-how-to-use-dps/index.html
I have…
- Added content to the "Schedule Your Move" page
- Implemented the "divider-heading" class used here as well as on other pages
- Added stubs for the subpages of Schedule Your Move
- Updated the subnavigation
1. Loaded the page in Chrome, Firefox, and Safari and verified that the layout looks right.
1. Tested each of the links on the page.
1. Tested each of the subnavigation entries.
Before:
After:
> First draft of “Schedule Your Move”, still missing iconography

- src/_assets/javascripts/components/moving-allowances-table.js
- src/_assets/javascripts/components/moving-allowances.js
- src/_assets/stylesheets/application.scss
- src/_assets/stylesheets/components/_section.scss
- src/_assets/stylesheets/elements/_table.scss
- src/_data/moving_allowance_categories.yml
- src/_data/pay_grades.yml
- src/moving-allowances/determine-your-allowance/index.html
- src/moving-allowances/index.html
I have…
**Note:** The test suite does not pass owing to some `<a href="#TODO">` anchors that will be updated later.
This pull request refines the JavaScript-powered enhancements to the "Determine Your Moving Allowance" page. User input from all three `<select>`s are used to determine which allowance table is shown and, within that allowance table, which rows and content are conditionally shown.
The JavaScript takes the "View details" anchor links that are in the `<table>`s' markup, grabs a reference to the linked node (based on the anchor's `href` / hash), clones that markup, and inserts it into the `<table>` _after_ the "View details" anchor. The tips content and the "View details" anchors are shown or hidden depending on the width of the viewport.
To verify the changes proposed in this …
> Additional enhancements to "Determine Your Moving Allowance" page

- src/_assets/stylesheets/application.scss
- src/_assets/stylesheets/elements/_list.scss
- src/_data/navigation.yml
- src/claims/faqs/index.html
- src/claims/index.html
I have…
**Note:** The test suite currently fails owing to some `<a href="#TODO">` anchors in page content.
This pull request adds content to the "Damage Claims Overview" page. It also adds a (for now) blank "Frequently Asked Questions" page organized under the Claims section.
1. clone this repo and set up development dependencies,
1. `git checkout add-damage-claims-content`,
1. `bundle exec rake jekyll:serve`,
1. point your Web browser of choice at http://localhost:4000/claims/,
1. observe that the site renders and behaves as shown in the (partial) screenshots below.
> Add Damage Claims Overview content

- src/_assets/stylesheets/components/_section.scss
- src/_layouts/page.html
- src/index.html
I have…
**Note:** The test suite currently fails owing to some `<a href="#TODO">` anchors in page content.
This pull request adds a version of the DPS login box from the homepage to interior pages beneath the sidebar navigation.
1. clone this repo and set up development dependencies,
1. `git checkout add-dps-login-to-sidebar`,
1. `bundle exec rake jekyll:serve`,
1. point your Web browser of choice at http://localhost:4000/claims/,
1. observe that the site renders and behaves as shown in the (partial) screenshots below.
> Add DPS login below sidebar navigation

- app/assets/config/manifest.js
- config/initializers/assets.rb
- package.json
I have…
This pull request switches asset precompilation configuration from `config/initializers/assets.rb` to `app/assets/config/manifest.js` which is a new(ish?) [Sprockets](https://github.com/rails/sprockets) thing. It's a little bit cleaner defining assets that require linking here than in `assets.rb`.
Practically speaking, assets that aren't automatically linked (by virtue of being `//= require`d or `@import`ed in `application.js` or `application.scss`) should be defined in `manifest.js`. I poked at the manifest's different directives (e.g. `link`, `link_tree`, etc.) and couldn't find a way to link _all_ assets of a given type provided by a gem. That means that for a third-party library like Leaflet (when included as a rails-assets.org gem), we'll need to declare each asset …
> Use manifest.js to configure assets for precompilation

- Gemfile
- Gemfile.lock
- LICENSE.md
- app/views/shared/_sidenav.html.erb
I have…
This pull request adds the [active_link_to](https://github.com/comfy/active_link_to) gem to the project which will simplify the highlighting of "active" navigation items.
1. `git checkout add-active_link_to-gem`,
1. `bin/rails server`, and
1. load up http://localhost:3000 in your Web browser of choice.
> Refactor navigation to use active_link_to gem

- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.erb
- app/views/shared/_nav.html.erb
- app/views/shared/_sidenav.html.erb
I have…
This pull request resolves #76 by adding secondary navigation to the "Moving with the Military" primary navigation item. It also (temporarily) loads [the uswds-rails gem](https://github.com/jgarber623/uswds-rails) from GitHub instead of RubyGems until a new version is released.
1. `git checkout rework-primary-navigation`,
1. `bin/rails server`, and
1. load up http://localhost:3000 in your Web browser of choice.
> Rework primary navigation

- app/assets/stylesheets/components/_header.scss
- app/assets/stylesheets/components/_navigation.scss
- app/assets/stylesheets/components/_section.scss
- app/assets/stylesheets/components/_sidenav.scss
- app/views/layouts/application.html.erb
- app/views/shared/_nav.html.erb
I have…
1. Hides nav bar accordion menus in the html so they dont flash briefly before the javascript runs
2. Makes the thick header bottom border consistent across layouts / pages
3. Hides the sidenav for narrower screens where it appears on the bottom of the page, and always show the top nav.
For issue #99
git checkout ui_polish,
load up http://localhost:3000/ in your Web browser of choice
play with screen size
go to another page
play with screen size
Header border narrow screen (before):
Header border narrow screen (after):
None-homepage header (before):
None-homepage header (after):
None-homepage narrow screen …
> Some UI polish

- app/assets/javascripts/components/weight-estimator.js
I have…
1. Removes the back tick used for js string templates. Hoping this unblocks deploy.
2. While I'm at it, update the packing time estimate with new figures from Jill.
2. git checkout remove_backtick
3. set up development dependencies according to CONTRIBUTING.md,
4. run bin/rails server, and
5. load up http://localhost:3000/weight-estimator in your Web browser of choice, calculate some weights
> Update packing estimates and dont use string templates

- app/assets/images/icons/pro-tip.svg
- app/assets/stylesheets/components/_layout.scss
- app/assets/stylesheets/components/_what_to_expect.scss
- app/assets/stylesheets/elements/_list.scss
- app/assets/stylesheets/elements/_typography.scss
- app/views/pages/moving-guide/retirees-separatees.html.erb
- app/views/pages/moving-guide/tdy.html.erb
- config/locales/en.yml
I have…
- Adds the retirees / separatees what to expect page
- Changes the page title font size for narrow width screens
This branches off of the tdy branch, since it uses some elements introduced there.
Issue #66
git checkout retirees
load up http://localhost:3000/moving-guide/retirees-separatees
wide:
narrow:
> Retirees and Separatees page

- app/assets/stylesheets/components/_sidenav.scss
- app/assets/stylesheets/components/_what_to_expect.scss
- app/views/pages/moving-guide/retirees-separatees.html.erb
- app/views/pages/moving-guide/tdy.html.erb
I have…
This pull request...
1. Makes the minimum screen size 800px before the sidenav moves to the top of the screen.
2. Makes the blue intro box full width with no margin for medium screen. I think this is fine to do it for medium width instead of 800px, since I didn't want to hardcode 800px in 2 places.
git checkout conus
load up http://localhost:3000/moving-guide/tdy and /retirees-separatees
Min screen size with side nav (800px):
Max screen size with side nav on top (799px):
Max screen size when blue box expands to full width:
> Change min width before sidenav moves to top of screen

- app/views/pages/moving-guide/conus.html.erb
I have…
I merged CONUS but forgot to update it to the new method of rendering the sidenav. This fixes that blooper.
git checkout tutorials
load up http://http://localhost:3000/moving-guide/conus
Before:
After:
> Fix conus sidenav

- app/assets/javascripts/components/coordinates-search-form.js
- app/assets/javascripts/components/coordinates-search.js
- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_layout.scss
- app/controllers/offices_controller.rb
- app/models/coordinates_search.rb
- app/models/installation_search.rb
- app/models/zip_code_search.rb
- app/views/offices/index.html.erb
- config/routes.rb
- spec/factories/installations.rb
- spec/requests/offices_spec.rb
I have…
This pull request refactors the "PPPO and Weight Scales Locations" page map and search functionality. New and updated features include:
- Users can search by ZIP code or plain text (e.g. "Fort Belvoir"). This first pass at plain text search is very rudimentary and my intention is to research PostgreSQL fuzzy searching and implement enhancements in the near future.
- Search results page URLs are much cleaner and consistent irrespective of "kind" of search (ZIP code, plain text, and geolocation). Under the covers, the controller action handles the complication of determining the "kind" of search and ultimately renders or redirects a page at a URL like `resources/locator-maps/38.933366,-77.030312`. This behavior is inspired by Google Maps' URL structure.
To verify the changes …
> Locator Map v3

- app/controllers/weight_estimator_controller.rb
- app/models/household_good.rb
- app/models/household_good_category.rb
- app/views/weight_estimator/_household_goods.html.erb
- app/views/weight_estimator/index.html.erb
I have…
This pull request refactors some of the code powering the Weight Estimator with an eye toward reducing database lookups.
1. `git checkout refactor-weight-estimator`,
1. navigate to http://localhost:3000/resources/weight-estimator and note reduced database lookups in console.
> Refactor weight estimator models, controller, and markup

- app/assets/stylesheets/components/_footer.scss
I have…
This pull request fixes the stretched footer logo
Issue #149
git checkout footer_ie10
load up http://localhost:3000/
Before:
After:
> Fix footer logo stretch

- app/assets/stylesheets/components/_footer.scss
I have…
This pull request fixes the footer logo for Chrome + Safari
git checkout footer_img,
load up http://localhost:3000 in Chrome, Safari, IE10, and Firefox
I also tested changing width to 20rem (larger than max-width) and tested in all the browsers, since the newer version of the web design standards reduces the max-width. If we upgrade to that version, things will not break.
> Set width for footer logo (fix chrome + safari)

- app/assets/stylesheets/components/_archive-banner.scss
- app/views/layouts/application.html.erb
I have…
This pull request adds a banner to the site notifying users of legacy content availability.
1. `git checkout add-archive-banner`,
1. run `bin/rails server`,
1. load up http://localhost:3000 and check out that banner!
> Add Archive banner

- .ebextensions/nginx.config
Add redirects in the nginx config from old move.mil pages to new pages if they exist, and otherwise to archive.move.mil. Tested by copying the file to the staging ec2 instance and testing that urls like http://move-mil-staging.us-east-1.elasticbeanstalk.com/dod/start_your_move/personally_procurred_move.cfm redirect
Issue #221
> Add nginx redirects

- .ebextensions/nginx.config
This PR updates the nginx configuration files, solving several redirection and 404-handling problems we noticed on our environments.
We'll need to test a deploy to staging to see if AWS/Elastic Beanstalk will properly overwrite the default `/etc/nginx/nginx.conf` file with our desired contents. It _should_ since we've observed `mime.types` being appropriately overwritten…
The default diff view is kinda heinous, so [the "split" view](https://github.com/deptofdefense/move.mil/pull/224/files?diff=split) might be easier on the eyes.
/cc @aileendds @hlieberman-gov
> Rework nginx config files

- app/assets/stylesheets/components/_weight-estimator.scss
I have…
This pull request makes some UI fixes that are necessary after removing the sidenav:
1. Make the tables full width. Now that they have more room, some dont take up full width and it looks weird that they're not all aligned.
2. Fix the input text alignment in IE
git checkout weight-est,
load up http://localhost:3000 in your Web browser of choice.
Before (IE10):
After (IE10):
> Weight estimator CSS fixes

- app/views/layouts/application.html.erb
I have…
This pull request updates the content in the gov banner, adding the TLS note.
1. `git checkout update-gov-banner`,
1. run `bin/rails server`,
1. load up http://localhost:3000 and check out that banner!
> Add TLS verbiage to gov banner

- app/assets/stylesheets/components/_special-items-navigation.scss
Issue #242
Also tested in Chrome and Safari
Before:
After:
> Fix entitlements table UI for IE10

- .ebextensions/nginx.config
- app/assets/stylesheets/components/_service-specific-info.scss
- app/views/service_specific_information/_air-force.html.erb
- spec/requests/service_specific_information_spec.rb
I have…
This pull request adds the AF video. Also updates the nginx config to allow iframes from youtube. Hopefully this is all that's needed but we'll see in staging.
Issue #261
To verify the changes proposed in this pull request
git checkout video,
run bin/rails server,
load up http://localhost:3000/resources/service-specific-information/air-force, watch video
<details><summary>Desktop</summary>
</details>
<details><summary>Mobile</summary>
</details>
> Add AF video to service page

- app/assets/stylesheets/components/_carousel.scss
- app/assets/stylesheets/components/_tutorial.scss
I have…
This pull request fixes the tutorial UI for narrow screen widths
Issue #271 
git checkout locator-maps-v4,
run bin/rails server,
load up http://localhost:3000/tutorials
before:
after:
> Fix tutorial buttons overlapping with title

- app/controllers/tutorials_controller.rb
I have…
Instead of showing a 500, if someone goes to www.move.mil/tutorials/some-tutorial-that-doesnt-exist, redirect to /tutorials.
Google currently indexes some of the old tutorials and if someone clicks those links they get a 500.
Issue #281 
git checkout tutorials,
load up http://localhost:3000/tutorials/bleh
> Redirect to /tutorials for bad tutorial IDs instead of 500

- db/seeds/tutorials.yml
This is a simple change, very similar to the substantive fix recently merged in PR #373
I have…
- Updates the text in two places on Slide #9 of the "Create a Shipment" tutorial.
- See [Issue #341 ](https://github.com/deptofdefense/move.mil/issues/341) for detail.
- Note: attribution already covered by @rich-allen-gov in PR #373
1. Run `bundle exec rake db:reset` to verify that all data was dropped, and reseeded correctly.
1. Ensure content updates appear as expected. 
1. Capture changes with screenshot (below)
BEFORE:
AFTER:
> updated tutorial seed data text per issue #341

- db/seeds/entitlements.yml
I have…
This is a very small change to entitlements data. The rank names in the entitlements are used in places where an **individual** user is asked for their rank - the entitlements page and the PPM estimator page. Therefore, the rank name should be singular, not plural. ("Civilian Employee" was already singular.)
1. git checkout `rank-singular`,
1. run `bin/rails db:setup`,
> Singular, not plural, ranks in entitlement data

- app/views/pages/moving-guide/conus.html.erb
Addresses #390. 
I have…
This pull request rearranges the words at the end of the "Loading / Moving Day" section in "What To Expect" for CONUS moves. It no longer implies signing in the remarks section.
1. git checkout `wte_remarks_signing`,
Before:
After:
> What To Expect: Loading / Moving Day - clear up confusion about signing in the remarks section

- lib/data/faqs.yml
I have…
- updates the FAQ content in After the Move for What type of surveys...
1. navigate to FAQs > After the Move > What type of surveys can I be expected to fill out?
2. click on the faq accordion to reveal the answer content, the new content should read,
"At the end of your move, you are required to fill out the customer satisfaction survey. This provides the Personal Property offices with direct feedback on your moving company. Be honest and leave comments – if they were a great mover we want to make sure they get the chance to work with members and their families in the future. If they were not so great… we want to make sure they don’t receive future opportunities."
before
after
> Feature 394 update faq after the move type of survey

- app/assets/stylesheets/components/_ppm-estimator.scss
- app/controllers/ppm_estimator_controller.rb
- app/models/ppm_estimator.rb
- app/views/ppm_estimator/_estimate_table.html.erb
- app/views/ppm_estimator/index.html.erb
- spec/requests/ppm_estimator_spec.rb
Addresses #415.
I have…
This pull request removes the branch of service input field from the PPM Estimator, as all services now offer up to a 60% advance. It also adjusts the formatting of the output slightly so that the "Your Details:" and rank strings fit on the same line more often.
1. git checkout `common-advance-60`,
> PPM Estimator: Remove branch of service field, as all services now offer 60% advance

- app/views/ppm_estimator/index.html.erb
- app/views/weight_estimator/_household_goods.html.erb
- app/views/weight_estimator/index.html.erb
Addresses #374.
I have…
This pull request sets the apporpriate attributes on the PPM Estimator and Weight Estimator forms so that mobile browsers will get the numeric-only keyboard when entering quantities, ZIP codes, dates, and weights.
1. git checkout `numeric-only-inputs`,
<details><summary>PPM Estimator - zip code field - before (iOS Safari)</summary>
</details>
<details><summary>PPM Estimator - zip code field - after (iOS Safari)</summary>
</details> …
> Numeric-only inputs

- app/assets/stylesheets/elements/_inputs.scss
- app/views/ppm_estimator/index.html.erb
- app/views/weight_estimator/_household_goods.html.erb
- app/views/weight_estimator/index.html.erb
I have…
This pull request resolves several small UI bugs introduced by #417. See screenshots below for some examples.
1. Numeric input fields in WebKit browsers displayed number spinners which (on the weight estimator) would overlay the user's input value.
2. Numeric input fields lacked a `min="0"` which would (on the front-end anyway) allow users to spin the input below zero.
The changes here update numeric inputs on the [Weight Estimator](https://www.move.mil/resources/weight-estimator) and on the [PPM Estimator](https://www.move.mil/resources/ppm-estimator).
1. `git checkout …
> Fix numeric input UI bugs introduced in PR #417
