deptofdefense/move.mil

src/_assets/stylesheets/components/_layout.scss
src/_assets/stylesheets/components/_section.scss
src/_assets/stylesheets/elements/_typography.scss
src/index.html

*Note:* the test suite currently does not pass, owing to some `<a href="#TODO">` anchors that will be addressed later.
This pull request implements a first pass buildout of the homepage. There are a number of details (replacing placeholder `<a href="#TODO">`, adding imagery, etc.) left to implement that will be addressed in future pull requests.
1. clone this repo and set up development dependencies,
1. `git checkout build-homepage`,
1. `bundle exec rake jekyll:serve`,
1. point your Web browser of choice at http://localhost:4000, and
1. observe that the homepage renders and behaves as shown in the screenshots below.

Homepage buildout

---

src/claims/index.html
src/schedule-your-move/index.html

I have…
This pull request fixes some spelling errors, missing commas, and awkward language.
1. Read the claims or schedule your move pages.

Spelling, grammar, copy-editing

---

.gitignore
CONTRIBUTING.md

Updates the install instructions to mention Postgres.app.

Contributing updates

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_approvals-list.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_layout.scss
app/assets/stylesheets/elements/_table.scss
app/views/layouts/_sidenav.html.erb
app/views/pages/moving-guide.html.erb
config/locales/en.yml

I have…
This pull request adds the Moving Guide page content and updates styling accordingly. See the screenshots below for a better look at the page.
1. `git checkout moving-guide-page`,
1. `bin/rails server`, and
1. load up http://localhost:3000/moving-guide in your Web browser of choice.

Build out Moving Guide page

---

app/assets/javascripts/components/tabs.js
app/views/shared/_service_emblems_list.html.erb

Addresses #58.
I have…
- Adds anchors to the links associated with the branch logos at the bottom of the homepage
- Checks for anchors in the document's URL on loading and goes to the appropriate tab panel, if one is appropriately named, otherwise still loads the first panel
1. git checkout `homepage-to-svc-specific`,
1. load up [http://localhost:3000](http://localhost:3000) in your Web browser of choice.

Go to service-specific tab when clicking on branch icon on homepage

---

db/seeds/tutorials.yml

I have…
This pull request resolves #75, updating the Schedule A Move tutorial content.
1. `git checkout update-schedule-a-move-tutorial-content`,
1. `bin/rails server`, and
1. load up http://localhost:3000/tutorials in your Web browser of choice.

Update Schedule A Move tutorial content

---

app/controllers/service_specific_information_controller.rb
app/controllers/tutorials_controller.rb
app/models/service_specific_post.rb
app/views/service_specific_information/_post.html.erb
app/views/service_specific_information/index.html.erb

I have…
This pull request optimizes a few Active Record queries by taking advantage of [AR's eager loading features](http://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations), refactoring pieces of models, controllers, and views.
1. `git checkout optimize-active-record-queries`,
1. run `bin/rails rake`,
1. run `bin/rails brakeman`,
1. run `bin/rails rubocop`,
1. run `bin/rails server`,
1. load up http://localhost:3000 in your Web browser of choice and observe that everything works as it always has!

Optimize Active Record queries

---

app/views/service_specific_information/index.html.erb
db/seeds/branch_of_service_contacts.yml

I have…
This PR resolves #114 by updating the contact information in `db/seeds/branch_of_service_contacts.yml`.
1. `git checkout update-air-force-contact-info`,
1. run `bin/rails server`,
1. load up http://localhost:3000/service-specific-information#air-force in your Web browser of choice and observe updated contact information in the sidebar.

Update Air Force retiree contact info

---

Gemfile
Gemfile.lock

I have…
This was used in the sidenav which is gone so it's obsolete. Issue #125
1. clone this repo
2. git checkout remove_active_link_to
3. set up development dependencies according to CONTRIBUTING.md,
4. run bin/rails server, and
5. load up http://localhost:3000 in your Web browser of choice

Remove active_link_to gem

---

app/assets/stylesheets/components/_customer-service.scss
app/assets/stylesheets/components/_layout.scss
app/assets/stylesheets/components/_resources.scss
app/assets/stylesheets/components/_sidenav.scss
app/views/pages/moving-guide/tdy.html.erb
app/views/shared/_nav.html.erb

I have…
This pull request adds the what to expect TDY page: https://app.zeplin.io/project/596e69460294feaa7dcfb194/screen/5a00b835300e38be81fd71fe
Issue #65
git checkout tdy
load up http://localhost:3000/tdy in your Web browser of choice
Desktop 1:
Desktop 2:
Desktop 3:
Mobile:

What to expect TDY page

---

app/assets/stylesheets/components/_what_to_expect.scss
app/views/pages/moving-guide/conus.html.erb
app/views/shared/_login_banner.html.erb

I have…
Adds the CONUS page based on this design: https://app.zeplin.io/project/596e69460294feaa7dcfb194/screen/59fcad1b1ed6d9015cc40f57
Issue #142
git checkout conus
load up http://localhost:3000/moving-guide/conus
Desktop:
Mobile:

What to expect CONUS moves page

---

app/views/pages/homepage.html.erb
app/views/pages/moving-guide/conus.html.erb
app/views/shared/_login_banner.html.erb

I have…
This pull request changes the DPS login urls
Issue #163
To verify the changes proposed in this pull request...
git checkout tutorials
load up http://localhost:3000 and click all the login links

Change all the sign in to DPS link URLs

---

app/assets/stylesheets/components/_what_to_expect.scss
app/views/pages/moving-guide/conus.html.erb
app/views/pages/moving-guide/oconus.html.erb

I have…
This pull request adds the OCONUS page content based on the mock
Issue #64
git checkout tutorials
load up http://localhost:3000/moving-guide/oconus
Mobile:
Desktop:

OCONUS page

---

.elasticbeanstalk/config.yml
.travis.yml

Update EB config and Travis config for production

---

app/views/customer_service/index.html.erb
db/migrate/20171129161530_add_claims_url_to_branch_of_service_contacts.rb
db/schema.rb
db/seeds/branch_of_service_contacts.yml

I have…
This pull request makes the changes in issue #174 
git checkout customer-service
load up http://localhost:3000/customer-service in your Web browser of choice

Customer service design changes

---

app/assets/stylesheets/components/_header.scss
app/views/layouts/application.html.erb

I have…
This pull request removes the beta notice from the header.
1. git checkout `remove-beta-header`,
1. load up [http://localhost:3000](http://localhost:3000) in your Web browser of choice.
<details><summary>Click to show screenshot</summary>
</details>
<details><summary>Click to show screenshot</summary>
</details>

remove beta header

---

app/views/tutorials/index.html.erb
spec/requests/tutorials/index_spec.rb

Addresses #182.
I have…
This pull request comments out the existing tutorials and replaces it with coming soon text.
1. git checkout `tutorials-coming-soon`,
1. load up [http://localhost:3000](http://localhost:3000) in your Web browser of choice.
<details><summary>Click to show screenshot</summary>
</details>
<details><summary>Click to show screenshot</summary>
</details>

Tutorials: coming soon

---

app/views/pages/moving-guide/retirees-separatees.html.erb

I have…
This pull request makes the changes requested in issue #190
git checkout customer-service
load up http://localhost:3000/moving-guide/retirees-separatees

Make retirees content changes

---

app/views/pages/moving-guide/tips.html.erb

This PR updates content on the Moving Tips page, resolving #202.

Update Moving Tips content

---

.ebextensions/nginx.config
app/assets/javascripts/components/locator-map.js

Update Tile Server URL to use HTTPS

---

db/seeds/shipping_offices.json
db/seeds/transportation_offices.json

This PR resolves the Locator Map data issue outlined in #210.

Update NE JPPSO data

---

app/assets/stylesheets/components/_section.scss
app/assets/stylesheets/elements/_table.scss
app/models/entitlement.rb
app/views/entitlements/_entitlements_table.html.erb
app/views/entitlements/_special_item_information.html.erb
app/views/entitlements/index.html.erb
app/views/entitlements/show.html.erb
app/views/pages/resources.html.erb
db/seeds/entitlements.yml
spec/factories/entitlements.rb

I have…
This pull request implements the things in issue #183
git checkout customer-service
load up http://localhost:3000/entitlements
<details><summary>Wide screen</summary>
</details>
<details><summary>After searching civilians</summary>
</details>
<details><summary>Focus</summary>
</details>
<details><summary>OCONUS warning with focus</summary>
</details>
<details><summary>OCONUS warning without focus</summary>
</details>
<details><summary>narrow screen</summary>
</details>
<details><summary>Single rank #show screen</summary>
</details>

Entitlements design updates / content changes

---

db/seeds/branch_of_service_contacts.yml

Addresses #216.
I have…
This pull request fixes typos in two claims e-mail addresses.
1. git checkout `claims-email-typos`,
1. run `bin/rails db:drop db:setup`,
1. load up [http://localhost:3000](http://localhost:3000) in your Web browser of choice.

fix claims email address typos

---

db/seeds/branches_of_service.yml

Fixes the typo for issue #218. Tested by clicking the link on the customer service page

Fix navysup typo

---

app/assets/stylesheets/components/_customer-service.scss
app/views/customer_service/index.html.erb
app/views/pages/moving-guide/retirees-separatees.html.erb
app/views/shared/_service_emblems_list.html.erb

I have…
1. Adds some army conus claims text as requested by #188
2. Removes empty table rows used for adding margins.
3. Switches addresses to not be wrapped in <p> which adds extraneous line spacing and extra margins at the bottom
4. Removes id from service_specific_information_path() calls cause it's cleaner and I like it...
git checkout army_claims,
load up http://localhost:3000/customer-service
<details><summary>Desktop</summary>
</details>
<details><summary>Mobile</summary>
</details>

Army claims

---

app/views/offices/_urls.html.erb

Fix broken link helpers

---

app/assets/stylesheets/components/_moving-guide.scss
app/assets/stylesheets/elements/_table.scss
app/views/errors/not_found.html.erb
app/views/pages/moving-guide/claims.html.erb
app/views/shared/_nav.html.erb

I have…
This pull request adds the claims page based on the design. Issue #135
git checkout claims,
load up http://localhost:3000/moving-guide/claims
<details>
<summary>Desktop</summary>
</details>
<details>
<summary>Mobile</summary>
</details>

Claims page

---

app/views/customer_service/index.html.erb
app/views/entitlements/index.html.erb
app/views/entitlements/show.html.erb
app/views/pages/moving-guide.html.erb
app/views/pages/moving-guide/conus.html.erb
app/views/pages/moving-guide/nightmare-moves.html.erb
app/views/pages/moving-guide/oconus.html.erb
app/views/pages/moving-guide/retirees-separatees.html.erb
app/views/pages/moving-guide/tdy.html.erb
app/views/pages/moving-guide/tips.html.erb
app/views/service_specific_information/show.html.erb

We introduced this partial in https://github.com/deptofdefense/move.mil/pull/214, using it everywhere now

Use sidenav partial everywhere

---

app/assets/stylesheets/components/_pro-tip.scss
app/assets/stylesheets/components/_what_to_expect.scss
app/views/customer_service/index.html.erb
app/views/pages/moving-guide/_ppm-guide.html.erb
app/views/pages/moving-guide/claims.html.erb
app/views/pages/moving-guide/conus.html.erb
app/views/pages/moving-guide/nightmare-moves.html.erb
app/views/pages/moving-guide/oconus.html.erb
app/views/pages/moving-guide/retirees-separatees.html.erb
app/views/shared/_pro_tip.html.erb

We use this same component everywhere. Since @jgarber623-gov made me realize you could add children to a partial with yield, this makes more sense.

Create pro tip partial

---

app/views/pages/moving-guide/oconus.html.erb

Checklist skipped; modifications made to non-code areas of a template only.
This pull request fixes up some minor grammar errors on the OCONUS move page.

Minor grammar tweaks on OCONUS move page.

---

app/controllers/sitemap_controller.rb
app/views/sitemap/index.xml.builder
config/routes.rb
public/google9826929a5028a0d1.html
public/robots.txt
spec/requests/sitemap_spec.rb

I have…
This pull request adds a sitemap.xml file and references it in robots.txt. I couldn't figure out a good way to pull the file paths dynamically. The closest thing I found was something like this: https://gist.github.com/bantic/5688232 but it doesn't include any of the static pages.
Issue #221 
git checkout claims,
load up http://localhost:3000/sitemap.xml
<details><summary>generated xml</summary>
Aileens-MacBook-Pro:move.mil aileenchen$ curl http://localhost:3000/sitemap.xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"> …

Add sitemap.xml 

---

Gemfile
Gemfile.lock
app/assets/javascripts/components/coordinates-search.js
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/elements/_inputs.scss
app/views/entitlements/index.html.erb
app/views/layouts/application.html.erb
app/views/offices/index.html.erb

I have…
This pull request updates the version of USWDS Move.mil uses from 1.3.1 to 1.4.3.
Issue #213
git checkout uswds,
load up http://localhost:3000 in your Web browser of choice

Update to USWDS 1.4.3

---

db/seeds/faqs.yml

I have…
This pull request adds new FAQs in issue #215 
git checkout faq,
load up http://localhost:3000 in your Web browser of choice.

Add new FAQs

---

app/views/pages/homepage.html.erb

Update claims link on homepage

---

app/views/pages/moving-guide/civilians.html.erb
app/views/pages/moving-guide/conus.html.erb
app/views/pages/moving-guide/oconus.html.erb

Spelling / grammar fixes
Issue #269

Fix spelling

---

CONTRIBUTING.md
app/models/location.rb
db/seeds.rb
db/seeds/transportation_offices.json
spec/models/location_spec.rb

I have…
1. Fixes the bad longitude that caused the search bug
2. Add lat long range validation to the location model
3. Make seeding fail on validation failures instead of failing silently
git checkout db_validation,
set up development dependencies according to CONTRIBUTING.md, (make sure seeding succeeds)
load up http://localhost:3000, search for "germany" in locator map, check other data

Fix wrong lat long and validate seed data

---

CONTRIBUTING.md

I thought the original wording was kinda confusing so updating it.

Make SEEDS_ENC_KEY usage clearer in Contributing.md

---

app/views/entitlements/_special_item_information.html.erb
db/seeds/faqs.yml
db/seeds/tutorials.yml

Implement several content updates.
- Fixes #330 
- Fixes #340 
- Fixes #348

Miscellaneous content updates

---

lib/data/faqs.yml

I have…
- updates the FAQ content in Before the Move for What is unaccompanied baggage...
1. navigate to FAQs > Before the Move > What is unaccompanied baggage?
2. click on the faq accordion to reveal the answer content, the first paragraph in the content should read,
"This is part of the member's weight allowance that is separated from other Household Goods and is shipped via an expedited mode because it's needed immediately or soon after arrival at the destination and prior to the arrival of Household Goods. This typically occurs with an OCONUS move."
before
paragraph that will have changes
after …

updated answer content in unaccompanied baggage faq closes #393

---

lib/data/transportation_offices.json
lib/data/weight_scales.json

I have…
- Removes several duplicate (and even triplicate) transportation offices and weight scales.
- Corrects the hours of operation for several offices.
- Corrects the address of the Malmstrom AFB office.
1. git checkout `pppo_updates`,

Corrections to transportation offices and weight scales

---

lib/data/transportation_offices.json
lib/data/weight_scales.json

This pull request addresses Issues #422, #423 and #425 as well as two similar requests not captured in the Github issue queue. These changes have already been incorporated into the tools on the new Drupal rebuild, and this change will ensure integrity of the locations provided in the interim by the current live site.
I have…
- Updates an e-mail address for a PPPO in Petaluma that currently constitutes PII and is therefore not 508-compliant.
- Updates the name of a weight scale location from “John Palmer M/S” to “John Palmer Moving & Storage”
- Per #422, updates a variety of information for the Fort Leavenworth PPPO
- Per #423, updates the e-mail address and telephone number of the Miami Beach PPSO
- Per #425, updates the street address and hours of the Fort Carson PPPO …

update five locations in seed files
